<a href="https://colab.research.google.com/github/tuesdxyxx/tuesdxyxx/blob/main/ADVANCED_WEEK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Student Name

Please add your name to this markdown cell.

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://felicepstamaria.net/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Food to Sail Around the World",
  "description": "Five ships were selected to be the Armada de Maluco. Their destination was Maluco, also called the Spice Islands of today's Indonesia. Trinidad was the flagship with around 61 men to feed including Ferdinand Magellan, the fleet's chief. San Antonio the largest by tonnage had 57 men, the Concepcion where Sebastian Elcano was assigned had a crew of 44, the Victoria had 44, and the smallest ship the Santiago had 31. Daily rations were computed for 237 persons although the actual number sailing is uncertain because manifests are not identical. The food was to last two years. The fleet left on August 10, 1519. They should have food to last till August 9, 1521. Only the Victoria skippered by Elcano returned on September 6, 1522. Only 18 of the original voyagers survived. Hunger and starvation were enemies of all voyages, especially a voyage of exploration such as that of the Armada de Maluco.",
  "subject": "Armada de Maluco; Ferdinand Magellan; Sebastian Elcano; Trinidad; San Antonio; Concepcion; Victoria; Santiago; Spice Islands; Indonesia",
  "exhibition": "Magellan Menu",
  "source": "Commemorative currency.",
  "type": "Image;Still Image",
  "format": "image/png",
  "object_thumb": "https://lh3.googleusercontent.com/d/1LySqMGA0PAlq1gHp6FhXnLgs2EQTbCsp",
  "object_location": "https://lh3.googleusercontent.com/d/1LySqMGA0PAlq1gHp6FhXnLgs2EQTbCsp",
  "reference_url": "felicepstamaria.net/items/coll001.html"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://felicepstamaria.net/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "antonio pigafetta": 26,
        "cooking": 19,
        "cooking -- philippines": 13,
        "food -- philippines": 12,
        "voyages and travels": 11,
        "charles swan": 10,
        "eating": 10,
        "panay": 9,
        "diego berga\u00f1o": 9,
        "rice": 8,
        "chinese": 8,
        "food": 8,
        "salt": 8,
        "philippines -- history -- 1521-1896": 8,
        "spain -- colonies -- asia -- social life and customs": 8,
        "armada de maluco": 7,
        "spain -- colonies -- asia -- religious life and customs": 7,
        "william dampier": 7,
        "customs": 7,
        "philippines": 6,
        "preparation": 6,
        "cebu": 5,
        "coconut": 5,
        "antonio morga": 5,
        "augustinians": 5,
        "vegetables": 5,
        "peppers": 5,
        "history": 5,
        "domingo fernandez navarrete o.p.": 5,
        "fr. juan francisco de san antonio": 5,
        "fiesta": 5,
        "abuses": 5,
        "ferdinand magellan": 4,
        "victoria": 4,
        "fruit": 4,
        "trading": 4,
        "christianity": 4,
        "diego bobadilla": 4,
        "ingredients": 4,
        "labor": 4,
        "fasts and feasts -- catholic church": 4,
        "cooking, spanish": 4,
        "hunting": 4,
        "sebastian elcano": 3,
        "trinidad": 3,
        "spice islands": 3,
        "guam": 3,
        "roasting": 3,
        "spices": 3,
        "banana": 3,
        "chicken": 3,
        "cooking, philippine": 3,
        "cookery, filipino -- history": 3,
        "food habits -- philippines -- history": 3,
        "philippines -- social life and customs": 3,
        "fishes": 3,
        "jackfruit": 3,
        "wine": 3,
        "ships": 3,
        "beef": 3,
        "cattle": 3,
        "annona": 3,
        "pineapple": 3,
        "papaya": 3,
        "calamay": 3,
        "honey": 3,
        "sugarcane": 3,
        "juan de medina": 3,
        "fasts and feasts": 3,
        "cheese": 3,
        "cquilao (kilaw)": 3,
        "beans": 3,
        "citrus": 3,
        "philippine cuisine": 3,
        "herbs": 3,
        "food security": 3,
        "children": 3,
        "philippines -- colonial influence": 3,
        "catholic church -- missions -- philippines": 3,
        "wine and wine making -- philippines": 3,
        "brine": 3,
        "plate": 3,
        "injustice": 3,
        "preservation": 3,
        "sanlucar-noceda tagalog dictionary": 3,
        "plating": 3,
        "palm": 3,
        "tidore": 2,
        "spain": 2,
        "mutiny": 2,
        "rajah humabon": 2,
        "magellan": 2,
        "borneo": 2,
        "rajah siripada": 2,
        "bread": 2,
        "fernando magallanes": 2,
        "pigafetta": 2,
        "fermentation": 2,
        "guava": 2,
        "pork": 2,
        "rizal, jose -- 1861-1896": 2,
        "bagoong": 2,
        "santol": 2,
        "turron": 2,
        "milk": 2,
        "buyo": 2,
        "manila": 2,
        "intramuros": 2,
        "carambola": 2,
        "bananas": 2,
        "jesuits": 2,
        "spaniards": 2,
        "tapa": 2,
        "sigang": 2,
        "cooking (seafood)": 2,
        "salting of food": 2,
        "flour": 2,
        "southeast asia": 2,
        "cooking (vinegar)": 2,
        "pasitis": 2,
        "baka": 2,
        "quiso": 2,
        "formulas, recipes, etc. -- philippines": 2,
        "essays": 2,
        "manila (philippines) -- history -- congresses": 2,
        "gastronomy -- philippines -- exhibitions": 2,
        "gastronomy -- europe -- exhibitions": 2,
        "formulas, recipes, etc.": 2,
        "social sciences": 2,
        "philippines -- history": 2,
        "book review": 2,
        "melchor de los reyes": 2,
        "crops -- philippines": 2,
        "litchi": 2,
        "cooking (coconut)": 2,
        "water buffalo": 2,
        "agriculture -- philippines": 2,
        "haga\u030atn\u0303a (guam)": 2,
        "gifts": 2,
        "john read": 2,
        "batanes (philippines)": 2,
        "mango": 2,
        "philippines -- commerce -- spain": 2,
        "spain -- commerce -- philippines": 2,
        "filipinos -- agriculture": 2,
        "spain -- colonies -- asia -- economic conditions": 2,
        "natural resources -- philippines": 2,
        "fr. diego berga\u00f1o": 2,
        "sweet": 2,
        "boil": 2,
        "bamboo": 2,
        "don francisco gueruela": 2,
        "camarines": 2,
        "reform": 2,
        "colonialism": 2,
        "gervasio gironella": 2,
        "cultivation": 2,
        "missionaries": 2,
        "pedro murillo velarde": 2,
        "conversion": 2,
        "mass": 2,
        "admiral george anson": 2,
        "galleon trade": 2,
        "filipinas": 2,
        "manila-acapulco": 2,
        "snack": 2,
        "kakanin": 2,
        "bibingka": 2,
        "palitaw": 2,
        "chocolate": 2,
        "tagalog": 2,
        "herb": 2,
        "vegetable": 2,
        "bean": 2,
        "meat": 2,
        "pig": 2,
        "spanish-tagalog": 2,
        "market": 2,
        "palengke": 2,
        "noceda-sanlucar": 2,
        "san antonio": 1,
        "concepcion": 1,
        "santiago": 1,
        "indonesia": 1,
        "bastimiento": 1,
        "datu colambu": 1,
        "datu siauri": 1,
        "argentina": 1,
        "homonhon island, samar": 1,
        "limasawa": 1,
        "mazaua": 1,
        "leyte": 1,
        "patagonia": 1,
        "suluan island": 1,
        "cruxificion": 1,
        "basilica of santi nazaro e celso": 1,
        "lombardy": 1,
        "laghan snails": 1,
        "bornean sultan": 1,
        "rajah-sultan manzor": 1,
        "tidore island": 1,
        "pan": 1,
        "budbud": 1,
        "humas": 1,
        "kabog": 1,
        "visayan king": 1,
        "ceremony": 1,
        "cumingii": 1,
        "tabon bird": 1,
        "straw": 1,
        "king of cebu": 1,
        "jar": 1,
        "birthplace": 1,
        "portugal": 1,
        "villa real": 1,
        "sabrosa": 1,
        "zeubu": 1,
        "bughas": 1,
        "first voyage": 1,
        "knight of the order of rhodes": 1,
        "filipino diet": 1,
        "lapu-lapu": 1,
        "ferdinand magallanes": 1,
        "hara humamay": 1,
        "earthenware": 1,
        "sultan of sulu": 1,
        "king of borneo": 1,
        "baking": 1,
        "luzon": 1,
        "memoirs": 1,
        "giovan carvaio": 1,
        "malucho islands": 1,
        "homonhon island": 1,
        "juan sebastian elcano": 1,
        "sanlucar": 1,
        "seville": 1,
        "moluccas": 1,
        "coconut water": 1,
        "labuyo": 1,
        "brodo": 1,
        "ginger": 1,
        "gengibre": 1,
        "easter sunday": 1,
        "asia": 1,
        "nipa": 1,
        "tuba nio nipa": 1,
        "tuba wine": 1,
        "medical cannibalism": 1,
        "samar": 1,
        "rizal, jose, 1861-1896 -- correspondence": 1,
        "food preferences": 1,
        "children's book": 1,
        "morisqueta": 1,
        "tributes": 1,
        "rice tributes": 1,
        "natives, diet": 1,
        "lao-lao": 1,
        "tamban lao-lao": 1,
        "tawilis": 1,
        "garum": 1,
        "liquamen": 1,
        "mabolo": 1,
        "velvet apple": 1,
        "tamarind": 1,
        "sampaloc": 1,
        "nanca": 1,
        "pomegranates": 1,
        "grapes": 1,
        "swine": 1,
        "eggs": 1,
        "tuba": 1,
        "olive": 1,
        "pao": 1,
        "paho": 1,
        "safflower": 1,
        "saffron": 1,
        "nuts": 1,
        "pili": 1,
        "carabaos": 1,
        "quilitis": 1,
        "amaranto": 1,
        "atis": 1,
        "the boxer codex": 1,
        "charles boxer": 1,
        "asian cuisine": 1,
        "renaissance": 1,
        "pugo": 1,
        "buyo chewing": 1,
        "christmas": 1,
        "ulikba": 1,
        "women": 1,
        "men": 1,
        "culinary": 1,
        "culture": 1,
        "sucesos de las islas filipinas": 1,
        "quince": 1,
        "buchayo": 1,
        "syrups": 1,
        "palm sugar": 1,
        "root crops": 1,
        "camote": 1,
        "sweet potato": 1,
        "banig": 1,
        "dulang": 1,
        "sailboats": 1,
        "caracoa": 1,
        "pedro de montes": 1,
        "ignacio mujica": 1,
        "horacio de la costa": 1,
        "sto. ni\u00f1o de cebu": 1,
        "queseo": 1,
        "animal culture": 1,
        "miguel lopez de legaspi": 1,
        "rajah tup\u00e1s": 1,
        "food supply": 1,
        "taal island": 1,
        "batangas": 1,
        "milking": 1,
        "cheesemaking": 1,
        "calumpit": 1,
        "sugar plantations": 1,
        "trapiche": 1,
        "pampanga": 1,
        "acculturation": 1,
        "missions": 1,
        "laguna": 1,
        "nypa palm": 1,
        "nipa wine": 1,
        "nipa vinegar": 1,
        "hagonoy": 1,
        "cookies": 1,
        "pan de san nicolas": 1,
        "san nicolas fiesta": 1,
        "food production": 1,
        "colonial earnings": 1,
        "economy": 1,
        "business": 1,
        "lampahan": 1,
        "sanglal": 1,
        "laoya": 1,
        "logao (lugaw)": 1,
        "salabat": 1,
        "buchayo (bukayo)": 1,
        "marhuya (maruya)": 1,
        "pasiti": 1,
        "language adaptation": 1,
        "manhoya": 1,
        "tlaxcalli": 1,
        "nixtamal": 1,
        "tapay": 1,
        "ligis": 1,
        "soman (suman)": 1,
        "iloilo": 1,
        "alonso mentrida": 1,
        "manasao": 1,
        "cooking (fish)": 1,
        "dutch": 1,
        "spanish immigrants": 1,
        "spanish settlers": 1,
        "oranges": 1,
        "grain": 1,
        "food fusions": 1,
        "spanish empire": 1,
        "southeast asian": 1,
        "cacao": 1,
        "diego salcedo": 1,
        "koxinga": 1,
        "caffeine": 1,
        "bivalves": 1,
        "poultry": 1,
        "sweeteners": 1,
        "sabao (sabaw)": 1,
        "balaobalao": 1,
        "cangcong (kangkong)": 1,
        "pacsio (paksiw)": 1,
        "sinigang": 1,
        "shrimps": 1,
        "sausages": 1,
        "cababat": 1,
        "manruya": 1,
        "pinais": 1,
        "quiping (kiping)": 1,
        "pahiyas": 1,
        "laga": 1,
        "santan": 1,
        "bolotagac": 1,
        "adobo": 1,
        "marinades": 1,
        "lara": 1,
        "siling labuyo": 1,
        "pamitpit": 1,
        "cows": 1,
        "cooking (beef)": 1,
        "diet -- philippines": 1,
        "food habits -- philippines": 1,
        "hotel and restaurant management": 1,
        "philippine history": 1,
        "social studies -- study and teaching -- elementary education": 1,
        "social sciences -- study and teaching -- higher education": 1,
        "manila (philippines) -- social conditions -- congresses": 1,
        "manila (philippines) -- antiquities -- congresses": 1,
        "manila (philippines) -- in motion pictures -- congresses": 1,
        "philippines -- manila": 1,
        "bakeries -- philippines": 1,
        "bread industry -- philippines": 1,
        "baking -- philippines": 1,
        "boulangerie -- philippines": 1,
        "cuisson au four -- philippines": 1,
        "dictionary": 1,
        "filipino": 1,
        "vocabulary": 1,
        "well-being": 1,
        "happiness": 1,
        "philosophy": 1,
        "humanities": 1,
        "restaurants -- philippines -- quezon city -- history": 1,
        "community resilience": 1,
        "convenience food": 1,
        "disaster preparedness": 1,
        "food preservation": 1,
        "urban gardening": 1,
        "cultural property -- philippines": 1,
        "book preview": 1,
        "philippine heritage": 1,
        "food tourism": 1,
        "world war, 1939-1945": 1,
        "identity": 1,
        "service learning": 1,
        "philippines -- colonization": 1,
        "dugong": 1,
        "bataan (philippines)": 1,
        "mexican lime": 1,
        "cooking, creole": 1,
        "filipinos": 1,
        "hiking": 1,
        "dominicans -- missions": 1,
        "mount calavite (occidental mindoro, philippines)": 1,
        "baco island (oriental mindoro, philippines)": 1,
        "spain -- colonies -- history, military": 1,
        "philippines -- commerce -- china": 1,
        "china -- commerce -- philippines": 1,
        "edible birds' nest": 1,
        "calamian islands (palawan, philippines)": 1,
        "city planning -- religious aspects -- catholic church": 1,
        "parishes (canon law)": 1,
        "parishes (local government)": 1,
        "plowing": 1,
        "spain -- colonies -- asia -- officials and employees": 1,
        "revolutions": 1,
        "food -- philippines -- history": 1,
        "cygnet": 1,
        "epinephelus itajara": 1,
        "philippines -- commerce -- mariana islands": 1,
        "mariana islands -- commerce -- philippines": 1,
        "chamorro (micronesian people)": 1,
        "hum\u00e5tak (guam)": 1,
        "san telmo": 1,
        "breadfruit": 1,
        "cooking (breadfruit)": 1,
        "mariana islands": 1,
        "coconut palm": 1,
        "wine and wine making": 1,
        "goa arack": 1,
        "lagenaria siceraria": 1,
        "clara lapus": 1,
        "coconut oil": 1,
        "piracy": 1,
        "barter": 1,
        "sago": 1,
        "sago palms": 1,
        "cooking (sago)": 1,
        "durian": 1,
        "typhoons": 1,
        "deer -- philippines": 1,
        "mindanao (philippines)": 1,
        "rajah laut": 1,
        "ramadan": 1,
        "lifestyles": 1,
        "galleons -- philippines": 1,
        "co\u0302n so\u031bn island (vietnam)": 1,
        "exchange": 1,
        "cooking -- batanes (philippines)": 1,
        "bashee drink": 1,
        "wine and wine making -- batanes (philippines)": 1,
        "maguindanao (philippines)": 1,
        "commerce": 1,
        "mango -- manila (philippines)": 1,
        "philippines -- religious life and customs": 1,
        "salt -- manila (philippines)": 1,
        "fruit -- philippines": 1,
        "clothing and dress -- religious aspects -- catholic church": 1,
        "filipinos -- food": 1,
        "health": 1,
        "cooking, philippines": 1,
        "filipinos -- fishing": 1,
        "racially mixed people -- taxation": 1,
        "racially mixed people": 1,
        "food prices": 1,
        "spain -- colonies -- asia -- administration": 1,
        "social movements -- religious aspects -- catholic church": 1,
        "galleons": 1,
        "commerce -- history": 1,
        "manila (philippines) -- commerce -- china": 1,
        "china -- commerce -- manila (philippines)": 1,
        "salt -- philippines": 1,
        "tagalog language": 1,
        "canarium": 1,
        "filipinos -- attitudes": 1,
        "filipinos -- taxation": 1,
        "food portions": 1,
        "marine resources -- philippines": 1,
        "cebu (philippines)": 1,
        "fr. casimiro diaz": 1,
        "influenza": 1,
        "guagua": 1,
        "manuel blanco": 1,
        "bawang": 1,
        "onion": 1,
        "fr. venancio samson": 1,
        "fish": 1,
        "island": 1,
        "boiled": 1,
        "blanche": 1,
        "arsenio manuel": 1,
        "fire": 1,
        "mince": 1,
        "francisco de san antonio": 1,
        "dining table": 1,
        "bowl": 1,
        "porcelain": 1,
        "smell": 1,
        "leftovers": 1,
        "manners": 1,
        "casemiro diaz": 1,
        "gottfried kirch": 1,
        "comet": 1,
        "santa rosa de lima": 1,
        "smallpox": 1,
        "fernando manuel de bustillo bustamante y rueda": 1,
        "c. pajaron": 1,
        "real academia dela historia": 1,
        "revolt": 1,
        "jose villa": 1,
        "agrarian revolt": 1,
        "pedro enriquez": 1,
        "king ferdinand vi": 1,
        "antonio mozo": 1,
        "balugas": 1,
        "aetas": 1,
        "deer": 1,
        "revolts": 1,
        "sangley": 1,
        "mestizo": 1,
        "sweets": 1,
        "trade": 1,
        "conquista": 1,
        "spanish": 1,
        "francisco alcina": 1,
        "cuisine": 1,
        "real alcaiceria de san fernando": 1,
        "binondo": 1,
        "juan davila": 1,
        "bartolom\u00e9 brabo": 1,
        "pepper": 1,
        "british occupation": 1,
        "ignacio francisco alcina": 1,
        "historia de las islas e indios de bisayas": 1,
        "mexican": 1,
        "nicholas norton nicols": 1,
        "zamboanga": 1,
        "francisco leandro de viana": 1,
        "cinnamon": 1,
        "language": 1,
        "meals": 1,
        "condiments": 1,
        "fruits": 1,
        "orange": 1,
        "taste": 1,
        "flavor": 1,
        "noodles": 1,
        "leaves": 1,
        "bowls, coconut": 1,
        "spoon": 1,
        "traditions": 1,
        "drinks": 1,
        "alcohol": 1,
        "alak": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "felice prudente sta. maria": 25,
        "campus events management [ls]": 4,
        "ateneo de manila university": 3,
        "rainier a. ibana": 3,
        "philippine national historical society": 2,
        "michaela fenix": 2,
        "manila studies association": 2,
        "marya svetlana t. camacho": 2,
        "anvil publishing": 2,
        "spanish ministry of foreign affairs and cooperation": 2,
        "antonio sanchez de mora": 2,
        "erlinda enriquez panlilio": 1,
        "manuel baldemor": 1,
        "mika bacani": 1,
        "bryan koh": 1,
        "mariel ylagan garcia": 1,
        "bancom audiovision corporation": 1,
        "gilda cordero-fernando": 1,
        "bernadita reyes churchill": 1,
        "unesco national commission of the philippines": 1,
        "florentino hornedo": 1,
        "rainier ibana": 1,
        "rupert p. alonzo": 1,
        "joji o. racelis": 1,
        "wilfredo v. villacorta": 1,
        "josef teofisto yap": 1,
        "maya besa roxas": 1,
        "amy a. uy": 1,
        "jenny b. orillos": 1,
        "edgie polistico": 1,
        "rpd publications for the local government of quezon city": 1,
        "rolando o. borrinaga": 1,
        "megaworld museums": 1,
        "ige ramos design studio": 1,
        "helen orosa del rosario": 1,
        "xiao chua": 1,
        "margaux camaya": 1,
        "the global bookworm": 1,
        "ayala foundation, inc.": 1,
        "getty research institute": 1,
        "kunsthostorisches institut in florenz [max-planck-institut]": 1,
        "florentina h. capistrano-baker": 1,
        "meha priyadarshini": 1,
        "the kitchen bookstore": 1,
        "manila: people & places": 1,
        "mama sita's recipes": 1,
        "filipinas heritage library": 1,
        "upaa toronto": 1,
        "riverboy studios": 1
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 256,
        "image/png": 15,
        "video/mp4": 14,
        "application/pdf": 9
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- felice prudente sta. maria
- antonio pigafetta
- cooking
- food -- philippines
- voyages and travels

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below


This facet that shows up the most is "antonio pigafetta" it is used 26 times on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,description,subject,exhibition,source,type,format,object_thumb,object_location,reference_url,rights,rightsstatement,creator,date
0,Food to Sail Around the World,Five ships were selected to be the Armada de M...,Armada de Maluco; Ferdinand Magellan; Sebastia...,Magellan Menu,Commemorative currency.,Image;Still Image,image/png,https://lh3.googleusercontent.com/d/1LySqMGA0P...,https://lh3.googleusercontent.com/d/1LySqMGA0P...,felicepstamaria.net/items/coll001.html,NaN,NaN,NaN,NaN
1,Stocking for Two Years,The bastimiento (provisions) of the Armada de ...,Armada de Maluco; bastimiento,Magellan Menu,Collectible quincentennial coin.,Image;Still Image,image/png,https://lh3.googleusercontent.com/d/12rmgU0QZS...,https://lh3.googleusercontent.com/d/12rmgU0QZS...,felicepstamaria.net/items/coll002.html,NaN,NaN,NaN,NaN
2,Holy Week Abstinence,The expedition to the Spice Islands with Magel...,Ferdinand Magellan; Sebastian Elcano; Antonio ...,Magellan Menu,Commemorative collectible for the Quincentennial,Image;Still Image,image/png,https://lh3.googleusercontent.com/d/1yiT8HJEDC...,https://lh3.googleusercontent.com/d/1yiT8HJEDC...,felicepstamaria.net/items/coll003.html,NaN,NaN,NaN,NaN
3,Too Little,The Magellan expedition was one of discovery. ...,Ferdinand Magellan; Armada de Maluco; Guam; Sp...,Magellan Menu,Commemorative Magellan coin.,Image;Still Image,image/png,https://lh3.googleusercontent.com/d/1YaEEX5x6r...,https://lh3.googleusercontent.com/d/1YaEEX5x6r...,felicepstamaria.net/items/coll004.html,NaN,NaN,NaN,NaN
4,Out of Food,Calculating exactly how many men arrived on th...,Suluan Island; Cruxificion,Magellan Menu,CRUCIFIXION by Juan Flandes. 1519. Wikimedia. ...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1DsY8S9vEM...,https://lh3.googleusercontent.com/d/1DsY8S9vEM...,felicepstamaria.net/items/coll005.html,Public domain,https://creativecommons.org/publicdomain/mark/...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,NATIVE BOWLS,"Just as leaves, especially coconut fronds, wer...",Sanlucar-Noceda Tagalog dictionary; Plate; Pla...,Tagalog 1754,A polished coconut shell bowl. Contributor: Lu...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1HpoW3pTJ3...,https://lh3.googleusercontent.com/d/1HpoW3pTJ3...,felicepstamaria.net/items/coll290.html,NaN,NaN,NaN,2021-10-13
290,SPOONS,The 1754 roster of “cucharas” continues to inc...,Spoon; Cooking; Plating; Eating; Customs,Tagalog 1754,FSM photo,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/18iLBFBYhI...,https://lh3.googleusercontent.com/d/18iLBFBYhI...,felicepstamaria.net/items/coll291.html,NaN,NaN,NaN,2021-10-16
291,PISTA,Tagalog dictionaries earlier than the Noceda-S...,Noceda-Sanlucar; Fiesta; Customs; Traditions; ...,Tagalog 1754,A postcard showing a fiesta of the early 1900s...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1od_fNsxr_...,https://lh3.googleusercontent.com/d/1od_fNsxr_...,felicepstamaria.net/items/coll292.html,NaN,NaN,NaN,2021-10-20
292,BOOZE,The Sanlucar/Noceda Tagalog-Spanish dictionary...,Noceda-Sanlucar; Wine; Drinks; Alcohol; Alak,Tagalog 1754,A book for libraries of F&B lovers,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1g68nhDjSv...,https://lh3.googleusercontent.com/d/1g68nhDjSv...,felicepstamaria.net/items/coll293.html,NaN,NaN,NaN,2021-10-27
293,COOKING,We end the sampling of culinary words from the...,Cooking; Preparation; Bamboo; Coconut; Sanluca...,Tagalog 1754,Rice cookers are new Philippine kitchen paraph...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/163l8mLmsd...,https://lh3.googleusercontent.com/d/163l8mLmsd...,felicepstamaria.net/items/coll294.html,public domain,NaN,NaN,2021-10-30

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,description,subject,exhibition,source,type,format,object_thumb,object_location,reference_url,rights,rightsstatement,creator,date
7,Pig and Peacock,The special meal for visitors in Cebu as in mu...,Cebu; Antonio Pigafetta; Bornean Sultan;,Magellan Menu,Lapulapu on the RP P500 bill,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/15J_VnnZXP...,https://lh3.googleusercontent.com/d/15J_VnnZXP...,felicepstamaria.net/items/coll008.html,NaN,NaN,NaN,NaN
34,Hungry for Home,Pigafetta had been eating tropical Asian food ...,Antonio Pigafetta,Magellan Menu,“India Que Orientalists decitur et el Insular ...,Image;Still Image,image/png,https://lh3.googleusercontent.com/d/1ZQ4WsYyTe...,https://lh3.googleusercontent.com/d/1ZQ4WsYyTe...,felicepstamaria.net/items/coll035.html,NaN,NaN,NaN,NaN
204,Lucky Manila,The pirates depended on good weather to conduc...,Galleons -- Philippines; Côn Sơn Island (Vie...,Dampier 1686,View of Manila. Noveau voyage autour du monde ...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1KCr-QiyzE...,https://lh3.googleusercontent.com/d/1KCr-QiyzE...,felicepstamaria.net/items/coll205.html,NaN,NaN,NaN,2021-04-21
285,INGREDIENTS 5 continued,In the Spanish-Tagalog section of the dictiona...,Meat; Pig; Beef; Spanish-Tagalog; Market; Pale...,Tagalog 1754,Hitesh Dewani in Unsplash,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1fWP9XL4rg...,https://lh3.googleusercontent.com/d/1fWP9XL4rg...,felicepstamaria.net/items/coll286.html,NaN,NaN,NaN,2021-09-29
232,ALLIUM,The arrival of chile added piquancy to the Phi...,Manuel Blanco; Bawang; Onion,Pampaga 1732,Shallot. Dreamtime.com Public Domain,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1bCZNS1_lc...,https://lh3.googleusercontent.com/d/1bCZNS1_lc...,felicepstamaria.net/items/coll233.html,public domain,NaN,NaN,2021-07-03
274,MEXICAN MIX,"Tamal, champurrado, and chocolaté beverage had...",Mexican; Cooking; Preparation; Chocolate,Philippine Food 200,Recipe in photo was distributed all over the P...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1nBpGQwavI...,https://lh3.googleusercontent.com/d/1nBpGQwavI...,felicepstamaria.net/items/coll275.html,NaN,NaN,NaN,2021-11-26
9,Courtly Food,The Armada’s officials were allowed by Borneo’...,Armada de Maluco; Rajah Siripada,Magellan Menu,Vintage postal image of a peacock.,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/10l61LS82H...,https://lh3.googleusercontent.com/d/10l61LS82H...,felicepstamaria.net/items/coll010.html,public domain,https://creativecommons.org/publicdomain/mark/...,NaN,NaN
44,Slow Food: Philippine Culinary Traditions,A delicious servigin of nostalgic and informat...,"Cooking, Philippine",Publications,https://www.amazon.com/SLOW-FOOD-Philippine-Cu...,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1g41y7I9QL...,https://lh3.googleusercontent.com/d/1g41y7I9QL...,felicepstamaria.net/items/coll045.html,All rights reserved,NaN,Erlinda Enriquez Panlilio; Felice Prudente Sta...,2005
248,FRECKLES,Food heritage supporters can sustain Pampanga’...,Banana; Fruit,Pampaga 1732,FSM Photo,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1M-2lSnrOd...,https://lh3.googleusercontent.com/d/1M-2lSnrOd...,felicepstamaria.net/items/coll249.html,NaN,NaN,NaN,2021-08-21
139,Chile & Pepper,One principal objective of Spain’s colonial ve...,Spices; Peppers; Pamitpit,100 Philippine Food,Piper nigrum from “freepik.com”,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1iC1FUq8lH...,https://lh3.googleusercontent.com/d/1iC1FUq8lH...,felicepstamaria.net/items/coll140.html,public domain,NaN,NaN,NaN

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
cb_normalized[cb_normalized["subject"] == "Antonio Pigafetta"]

,title,description,subject,exhibition,source,type,format,object_thumb,object_location,reference_url,rights,rightsstatement,creator,date
13,Fake Face,Le voyage et navigation and Primo viaggio into...,Antonio Pigafetta,Magellan Menu,"Antonio Pigafetta, Primo viaggio intorno al mo...",Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1AhZVqljMU...,https://lh3.googleusercontent.com/d/1AhZVqljMU...,felicepstamaria.net/items/coll014.html,NaN,NaN,NaN,NaN
34,Hungry for Home,Pigafetta had been eating tropical Asian food ...,Antonio Pigafetta,Magellan Menu,“India Que Orientalists decitur et el Insular ...,Image;Still Image,image/png,https://lh3.googleusercontent.com/d/1ZQ4WsYyTe...,https://lh3.googleusercontent.com/d/1ZQ4WsYyTe...,felicepstamaria.net/items/coll035.html,NaN,NaN,NaN,NaN
49,Pigafetta's Philippine Picnic: Culinary Encoun...,Pigafetta's Philippine Picnic: Culinary Encoun...,Antonio Pigafetta,Publications,https://nhcp.gov.ph/pigafettas-philippine-picnic/,Image;Still Image,image/jpeg,https://lh3.googleusercontent.com/d/1fihNcJZxG...,https://lh3.googleusercontent.com/d/1fihNcJZxG...,felicepstamaria.net/items/coll050.html,All rights reserved,NaN,Felice Prudente Sta. Maria,2021


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.